[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/display/"
  status = 302

[[headers]]
  for = "/display/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/control/*"
  [headers.values]
    Cache-Control = "no-store"
